- hosts: kube-nodes
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['control1'].join_command }} >> node_joined.txt"
    - debug: msg="{{ node_joined.txt }}"
#      shell: kubeadm join 10.3.0.6:6443 --token nncxve.rzlgo0wp2t20qinr --discovery-token-ca-cert-hash sha256:62a9db148daab97316a99f0b433f37e3c0f61836bf8ef96ed905a95ee>
#      args:
#        chdir: $HOME
#        creates: node_joined.txt
