---
- hosts: master_node
  become: true
  tasks:
  - name: create volume
    command: kubectl create -f volume.yml
  - name: create mysql database        
    command: kubectl create -f mysql.yml
  - name: create backend deployment        
    command: kubectl create -f backend.yml
  - name: create frontend deployment       
    command: kubectl create -f frontend.yml
