---
- hosts: master_node
  become: false
  tasks:
  - name: create volume
    shell: chdir=/var/lib/jenkins/workspace/ansible_infrastructure_terraform/kubernetes kubectl create -f volume.yml
  - name: create mysql database        
    shell: chdir=/var/lib/jenkins/workspace/ansible_infrastructure_terraform/kubernetes kubectl create -f mysql.yml
  - name: delay
    shell: sleep 50
  - name: create backend deployment        
    shell: chdir=/var/lib/jenkins/workspace/ansible_infrastructure_terraform/kubernetes kubectl create -f backend.yml
  - name: create frontend deployment       
    shell: chdir=/var/lib/jenkins/workspace/ansible_infrastructure_terraform/kubernetes kubectl create -f frontend.yml
