variable "rg_name" {}
variable "location" {}
variable "vnet_name" {}
variable "cidr_vnet" {}
variable "subnet_name" {}
variable "cidr_subnet" {}
variable "vm_name" {}
variable "vm_size_node" {}
variable "vm_size_master" {}
